skyrim_commands = {
	0:{'BASE': 'animcam', 'PARAMS': None, 'DETAILS': 'Toggle animator camera'},
	1:{'BASE': 'psb', 'PARAMS': None, 'DETAILS': 'Player Spell Book'},
	2:{'BASE': 's1st', 'PARAMS': None, 'DETAILS': 'Shows 1st person model in 3rd person'},
	3:{'BASE': 'sucsm ', 'PARAMS': ['<number>'], 'DETAILS': 'Changes the speed of the free-flying camera (UFO cam)'},
	4:{'BASE': 'tai', 'PARAMS': None, 'DETAILS': 'Toggle AI'},
	5:{'BASE': 'tb', 'PARAMS': None, 'DETAILS': 'Toggle Borders'},
	6:{'BASE': 'tc', 'PARAMS': None, 'DETAILS': 'Toggle controls driven'},
	7:{'BASE': 'tcai', 'PARAMS': None, 'DETAILS': 'Toggle Combat AI'},
	8:{'BASE': 'tcl', 'PARAMS': None, 'DETAILS': 'Toggle collision (clipping, noclip)'},
	9:{'BASE': 'tdetect', 'PARAMS': None, 'DETAILS': 'Toggle AI Detection'},
	10:{'BASE': 'teofis', 'PARAMS': None, 'DETAILS': 'Toggle End-Of-Frame ImageSpace'},
	11:{'BASE': 'tfc ', 'PARAMS': ['<1>'], 'DETAILS': 'Freeflying camera'},
	12:{'BASE': 'tfow', 'PARAMS': None, 'DETAILS': 'Toggle Fog of War'},
	13:{'BASE': 'tg', 'PARAMS': None, 'DETAILS': 'Toggle grass'},
	14:{'BASE': 'tgm', 'PARAMS': None, 'DETAILS': 'Toggle god mode'},
	15:{'BASE': 'tim', 'PARAMS': None, 'DETAILS': 'Toggle immortal mode'},
	16:{'BASE': 'tll', 'PARAMS': None, 'DETAILS': 'Toggle LOD'},
	17:{'BASE': 'tm', 'PARAMS': None, 'DETAILS': 'Toggle menus (HUD)'},
	18:{'BASE': 'ts', 'PARAMS': None, 'DETAILS': 'Toggle sky'},
	19:{'BASE': 'tscr', 'PARAMS': None, 'DETAILS': 'Toggle script processing.'},
	20:{'BASE': 'tt', 'PARAMS': None, 'DETAILS': 'Toggle trees'},
	21:{'BASE': 'twf', 'PARAMS': None, 'DETAILS': 'Toggle wireframe'},
	22:{'BASE': 'tws', 'PARAMS': None, 'DETAILS': 'Toggle water system'},
	23:{'BASE': 'addperk ', 'PARAMS': ['<perk ID>'], 'DETAILS': 'Give a character the selected perk'},
	24:{'BASE': 'addspell ', 'PARAMS': ['<spell ID>'], 'DETAILS': "Add a specific spell to a character's available arsenal."},
	25:{'BASE': 'advlevel', 'PARAMS': None, 'DETAILS': "Advance a character's level by one."},
	26:{'BASE': 'AdvSkill ', 'PARAMS': ['<skill> ', '<nn>'], 'DETAILS': 'Advance the specified skill.'},
	27:{'BASE': 'completequest ', 'PARAMS': ['<quest ID>'], 'DETAILS': 'Complete the quest instantly.'},
	28:{'BASE': 'disable', 'PARAMS': None, 'DETAILS': "Don't render the selected object (includes actors.)"},
	29:{'BASE': 'dispelallspells', 'PARAMS': None, 'DETAILS': 'Dispel all temporary spell effects on target'},
	30:{'BASE': 'drop', 'PARAMS': None, 'DETAILS': "Force drop items from a character's inventory"},
	31:{'BASE': 'enable', 'PARAMS': None, 'DETAILS': 'Render the selected object (includes actors.)'},
	32:{'BASE': 'equipshout ', 'PARAMS': ['<Shout ID>'], 'DETAILS': 'Equipping the given shout.'},
	33:{'BASE': 'forceAV ', 'PARAMS': ['<attribute> ', '<nn>'], 'DETAILS': 'Force to modify the value of attribute'},
	34:{'BASE': 'getAV ', 'PARAMS': ['<attribute>'], 'DETAILS': 'Get value of attribute'},
	35:{'BASE': 'getAVinfo ', 'PARAMS': ['<attribute>'], 'DETAILS': 'Get value information of attribute'},
	36:{'BASE': 'getlevel ', 'PARAMS': ['<target>'], 'DETAILS': 'Get level of target'},
	37:{'BASE': 'getrelationshiprank ', 'PARAMS': ['<target>'], 'DETAILS': 'Get the relationship rank of two actors.'},
	38:{'BASE': 'getstage ', 'PARAMS': ['<quest ID>'], 'DETAILS': 'Show the current active quest stage.'},
	39:{'BASE': 'hasperk ', 'PARAMS': ['<perk ID>'], 'DETAILS': 'Check if the selected actor has a perk with the selected ID'},
	40:{'BASE': 'incPCS ', 'PARAMS': ['<skill name>'], 'DETAILS': 'Increase the given skill to the next level.'},
	41:{'BASE': 'kill ', 'PARAMS': ['<Actor ID (optional)>'], 'DETAILS': 'Kill the selected actor (NOT the optional Actor ID).'},
	42:{'BASE': 'lock ', 'PARAMS': ['<level>'], 'DETAILS': 'Lock targeted object (i.e. door, container) with a difficulty of <level>.'},
	43:{'BASE': 'MarkForDelete', 'PARAMS': None, 'DETAILS': 'Delete an object.'},
	44:{'BASE': 'modAV ', 'PARAMS': ['<attribute> ', '<nn>'], 'DETAILS': 'Modify value of attribute by <nn> amount'},
	45:{'BASE': 'moveto ', 'PARAMS': ['<actor ID>'], 'DETAILS': 'Move a character to specified actor and vice versa.'},
	46:{'BASE': 'movetoqt ', 'PARAMS': ['<quest ID>'], 'DETAILS': 'Move to quest target'},
	47:{'BASE': 'openactorcontainer 1', 'PARAMS': None, 'DETAILS': "Open a character's inventory."},
	48:{'BASE': 'placeatme ', 'PARAMS': ['<actor/object ID>'], 'DETAILS': 'Spawn specified actor or object at current position.'},
	49:{'BASE': 'playidle ', 'PARAMS': ['<idle ID>'], 'DETAILS': 'Play an animation (idle) on the specified actor.'},
	50:{'BASE': 'removeitem ', 'PARAMS': ['<item ID> ', '<count>'], 'DETAILS': "Remove the specified amount of an item from a character's inventory."},
	51:{'BASE': 'removeperk ', 'PARAMS': ['<perk ID>'], 'DETAILS': "Remove the specified perk from a character's skills."},
	52:{'BASE': 'removespell ', 'PARAMS': ['<spell ID>'], 'DETAILS': "Removes a specific spell from a character's spell book. Also works with powers, abilities, blessings, and diseases, but not shouts"},
	53:{'BASE': 'resetAI', 'PARAMS': None, 'DETAILS': "Reset an NPC's AI."},
	54:{'BASE': 'resethealth', 'PARAMS': None, 'DETAILS': 'Restore a character to full health.'},
	55:{'BASE': 'resetinventory', 'PARAMS': None, 'DETAILS': "Reset a container or a character's inventory."},
	56:{'BASE': 'resurrect ', 'PARAMS': ['<1>'], 'DETAILS': 'Resurrect target actor'},
	57:{'BASE': 'say ', 'PARAMS': ['<dialog topic ID>'], 'DETAILS': 'Makes the targeted actor say a specific dialog topic.'},
	58:{'BASE': 'setactoralpha ', 'PARAMS': ['<0–100>'], 'DETAILS': "Change the selected actor's alpha/opacity."},
	59:{'BASE': 'setAV ', 'PARAMS': ['<attribute> ', '<nn>'], 'DETAILS': 'Set value of attribute'},
	60:{'BASE': 'setghost ', 'PARAMS': ['<0 or 1>'], 'DETAILS': 'Set ghost mode for the targeted NPC.'},
	61:{'BASE': 'setgs ', 'PARAMS': ['<setting> ', '<value>'], 'DETAILS': 'Set game setting.'},
	62:{'BASE': 'setnpcweight ', 'PARAMS': ['<0–100>\n(snpcw)'], 'DETAILS': 'Set the weight of the selected NPC and updates the model to reflect the new weight.'},
	63:{'BASE': 'setownership ', 'PARAMS': ['<ID>'], 'DETAILS': 'Sets ownership of the targeted item.'},
	64:{'BASE': 'setrace ', 'PARAMS': ['<race>'], 'DETAILS': "Change a character's race."},
	65:{'BASE': 'setscale ', 'PARAMS': ['<#>'], 'DETAILS': 'Scale size of target.'},
	66:{'BASE': 'setstage ', 'PARAMS': ['<quest ID> ', '<stage #>'], 'DETAILS': 'Set the current stage of the given quest.'},
	67:{'BASE': 'setunconscious ', 'PARAMS': ['<integer>'], 'DETAILS': 'A value of 1 will be unconscious'},
	68:{'BASE': 'inv/showinventory', 'PARAMS': None, 'DETAILS': "Display the base IDs of every item in a character's inventory."},
	69:{'BASE': 'sifh ', 'PARAMS': ['<#>'], 'DETAILS': 'Set whether an actor should ignore friendly hits.'},
	70:{'BASE': 'sqs ', 'PARAMS': ['<quest ID>'], 'DETAILS': 'Display stages of a quest'},
	71:{'BASE': 'stopcombat', 'PARAMS': None, 'DETAILS': 'Stop combat with a targetted NPC'},
	72:{'BASE': 'str ', 'PARAMS': ['<0–1.000000>'], 'DETAILS': 'Set the refraction value of the selected target.'},
	73:{'BASE': 'teachword ', 'PARAMS': ['<word>'], 'DETAILS': 'Teach a dragon shout.'},
	74:{'BASE': 'unequipitem ', 'PARAMS': ['<Item baseID>'], 'DETAILS': 'Unequip item from selected NPC'},
	75:{'BASE': 'unlock', 'PARAMS': None, 'DETAILS': 'Unlock the targeted object.'},
	76:{'BASE': 'unlockword ', 'PARAMS': ['<word>'], 'DETAILS': 'Unlock a dragon shout.'},
	77:{'BASE': 'bat', 'PARAMS': None, 'DETAILS': 'Execute a batch file'},
	78:{'BASE': 'caqs', 'PARAMS': None, 'DETAILS': 'Complete all quest stages'},
	79:{'BASE': 'coc', 'PARAMS': None, 'DETAILS': 'Transport to <cellname>'},
	80:{'BASE': 'cow', 'PARAMS': None, 'DETAILS': 'Transports to cell <cell x, cell y> in <worldspace>'},
	81:{'BASE': 'csb', 'PARAMS': None, 'DETAILS': 'Clear screen blood'},
	82:{'BASE': 'fov', 'PARAMS': None, 'DETAILS': 'Set fov <angle>'},
	83:{'BASE': 'fw', 'PARAMS': None, 'DETAILS': 'Force Weather'},
	84:{'BASE': 'GetGlobalValue ', 'PARAMS': ['<Variable>'], 'DETAILS': 'Returns the value of a single global game setting.'},
	85:{'BASE': 'GetPCMiscStat ', 'PARAMS': ['<Stat>'], 'DETAILS': 'Returns the value of the (typically meaningless) stats shown in the ESC menu.'},
	86:{'BASE': 'help', 'PARAMS': None, 'DETAILS': 'Returns the IDs of all items, spells, game settings, etc. which have the entered text in their name.'},
	87:{'BASE': 'killallactors', 'PARAMS': None, 'DETAILS': 'Kill all actors.'},
	88:{'BASE': 'load', 'PARAMS': None, 'DETAILS': 'Loads <name> gamesave.'},
	89:{'BASE': 'ModPCMiscStat ', 'PARAMS': ['<Stat> ', '<nn>'], 'DETAILS': 'Adjusts the value of the (typically meaningless) stats shown in the ESC menu by <nn> amount.'},
	90:{'BASE': 'pcb', 'PARAMS': None, 'DETAILS': 'Purge cell buffer'},
	91:{'BASE': 'prid ', 'PARAMS': ['<RefID>'], 'DETAILS': 'Pick reference by ID'},
	92:{'BASE': 'qqq', 'PARAMS': None, 'DETAILS': 'Fast quit.'},
	93:{'BASE': 'resetinterior ', 'PARAMS': ['<cellID>'], 'DETAILS': 'Reset an entire cell.'},
	94:{'BASE': 'refini', 'PARAMS': None, 'DETAILS': 'Refreshes all settings.'},
	95:{'BASE': 'resetquest ', 'PARAMS': ['<questID>'], 'DETAILS': 'Reset a quest.'},
	96:{'BASE': 'saq', 'PARAMS': None, 'DETAILS': 'Start all quests'},
	97:{'BASE': 'save', 'PARAMS': None, 'DETAILS': 'Write <name> gamesave.'},
	98:{'BASE': 'saveini', 'PARAMS': None, 'DETAILS': 'Save settings to file.'},
	99:{'BASE': ' set gamehour to ##', 'PARAMS': None, 'DETAILS': 'Sets the time of the day'},
	100:{'BASE': ' set timescale to ', 'PARAMS': ['<qty>'], 'DETAILS': 'Sets the speed of how fast time advances in-game'},
	101:{'BASE': 'setplayerrace', 'PARAMS': None, 'DETAILS': 'Set player race.'},
	102:{'BASE': 'SexChange', 'PARAMS': None, 'DETAILS': "Switches the player or an NPC's gender"},
	103:{'BASE': 'SGTM', 'PARAMS': None, 'DETAILS': 'Changes the Gametime Multiplier to a specified value for slow motion, and fast forward type effects'},
	104:{'BASE': 'ShowGlobalVars', 'PARAMS': None, 'DETAILS': 'Shows all current game variables'},
	105:{'BASE': 'ShowMessage', 'PARAMS': None, 'DETAILS': 'Shows a message'},
	106:{'BASE': 'showracemenu', 'PARAMS': None, 'DETAILS': 'Opens the character creation menu.'},
	107:{'BASE': 'showracemenu ', 'PARAMS': ['<race>'], 'DETAILS': "Changes the player's race."},
	108:{'BASE': 'spf ', 'PARAMS': ['<file name>'], 'DETAILS': 'Save PC Face'},
	109:{'BASE': 'sqo', 'PARAMS': None, 'DETAILS': 'Itemizes quest objectives and their states'},
	110:{'BASE': 'sqt', 'PARAMS': None, 'DETAILS': 'List quest ids and targets'},
	111:{'BASE': 'sqv ', 'PARAMS': ['<questID>'], 'DETAILS': 'Show quest variables'},
	}